services:
  matrix-bridge:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: matrix-bridge
    restart: unless-stopped
    environment:
      - MXBIRDGE_MASTER_KEY=${MASTER_KEY:-}
    volumes:
      - ../config:/app/config
      - ../store:/app/store
      - ../media:/app/media
